name = "aws-docs-graph"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "cd web && npm install && npm run build"

[vars]
NEXT_PUBLIC_API_URL = "https://aws-docs-graph-production.up.railway.app"
