FROM python:3.12-slim

WORKDIR /app

ARG CACHEBUST=3

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir sentence-transformers

COPY app/ ./app/

COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
